export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const ADD_FLASH_MESSAGE_MODAL = 'ADD_FLASH_MESSAGE_MODAL';
export const DELETE_FLASH_MESSAGE_MODAL = 'DELETE_FLASH_MESSAGE_MODAL';